events {}

http {
  server {
    listen 8080;

    # webterm on port 4001
    location /terminal {
      proxy_pass http://127.0.0.1:4001/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    # nova-os on port 4000
    location / {
      proxy_pass http://127.0.0.1:4000/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }
  }
}
